mysql:
  username: "root"
  password: "030123"
  network_protocal: "tcp"
  server_address: "127.0.0.1"
  server_port: "3306"
  database_name: "gin_uploadphoto"
  character: "utf8mb4"
redis:
  addr : "127.0.0.1:6379"
  password: ""
  db: 0
  poolSize: 200
  midIdleConn: 50
