info:
  contact: {}
  title: APIphoto_server
  version: V1.0
paths:
  /user/CreateUser:
    post:
      parameters:
      - description: UserName
        in: formData
        name: UserName
        type: string
      - description: Password
        in: formData
        name: Password
        type: string
      - description: RePassword
        in: formData
        name: RePassword
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
        "400":
          description: code","message"}
          schema:
            type: string
      summary: add user
      tags:
      - user management
  /user/LoginInUser:
    post:
      parameters:
      - description: UserName
        in: formData
        name: UserName
        type: string
      - description: Password
        in: formData
        name: Password
        type: string
      responses:
        "200":
          description: code","message","token"}
          schema:
            type: string
        "400":
          description: code","message","token"}
          schema:
            type: string
      summary: login in user
      tags:
      - user management
  /user/upload-avatar:
    post:
      description: 上传用户头像接口（支持JPEG/PNG格式，最大30MB）
      parameters:
      - description: 头像文件（支持JPEG/PNG格式）
        in: formData
        name: avatar
        required: true
        type: file
      - description: 用户id
        in: formData
        name: id
        required: true
        type: string
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
        "400":
          description: code","message"}
          schema:
            type: string
        "413":
          description: code","message"}
          schema:
            type: string
        "500":
          description: code","message"}
          schema:
            type: string
      summary: 上传用户头像
      tags:
      - User Home Message
swagger: "2.0"
