info:
  contact: {}
  title: APIphoto_server
  version: V1.0
paths:
  /api/photo/upload:
    post:
      description: 接收用户上传的图片文件并存储到指定用户目录，同时记录文件元信息到数据库
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 要上传的图片文件(支持JPG/PNG)
        in: formData
        name: photo
        required: true
        type: file
      - description: 用户id
        in: formData
        name: id
        required: true
        type: string
      - description: 图片描述信息
        in: formData
        name: description
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
        "400":
          description: code","message"}
          schema:
            type: string
        "401":
          description: code","message"}
          schema:
            type: string
        "500":
          description: code","message"}
          schema:
            type: string
      summary: 用户上传图片接口
      tags:
      - Photo control
  /user/CreateUser:
    post:
      parameters:
      - description: UserName
        in: formData
        name: UserName
        type: string
      - description: Password
        in: formData
        name: Password
        type: string
      - description: RePassword
        in: formData
        name: RePassword
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
        "400":
          description: code","message"}
          schema:
            type: string
      summary: add user
      tags:
      - user management
  /user/LoginInUser:
    post:
      parameters:
      - description: UserName
        in: formData
        name: UserName
        type: string
      - description: Password
        in: formData
        name: Password
        type: string
      responses:
        "200":
          description: code","message","id","token"}
          schema:
            type: string
        "400":
          description: code","message","id","token"}
          schema:
            type: string
      summary: login in user
      tags:
      - user management
  /user/upload-avatar:
    post:
      description: 上传用户头像接口（支持JPEG/PNG格式，最大30MB）
      parameters:
      - description: 头像文件（支持JPEG/PNG格式）
        in: formData
        name: avatar
        required: true
        type: file
      - description: 用户id
        in: formData
        name: id
        required: true
        type: string
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
        "400":
          description: code","message"}
          schema:
            type: string
        "413":
          description: code","message"}
          schema:
            type: string
        "500":
          description: code","message"}
          schema:
            type: string
      summary: 上传用户头像
      tags:
      - User Home Message
  /user/upload_self-introduce:
    post:
      description: 用户更新自我介绍信息接口（需Token认证）
      parameters:
      - description: 用户自我介绍内容
        in: formData
        name: selfIntroduce
        required: true
        type: string
      - description: 用户id
        in: formData
        name: id
        required: true
        type: string
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: code", "id","message"}
          schema:
            type: string
        "400":
          description: code", "id","message"}
          schema:
            type: string
        "500":
          description: code", "id","message"}
          schema:
            type: string
      summary: 更新用户自我介绍
      tags:
      - User Home Message
  /user/upload_user-email:
    post:
      description: 用户更新用户邮箱接口（需Token认证）
      parameters:
      - description: 用户邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 用户id
        in: formData
        name: id
        required: true
        type: string
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: code", "message"}
          schema:
            type: string
        "400":
          description: code", "message"}
          schema:
            type: string
        "500":
          description: code", "message"}
          schema:
            type: string
      summary: 更新用户邮箱
      tags:
      - user management
  /user/upload_user-phone:
    post:
      description: 用户更新用户电话号接口（需Token认证）
      parameters:
      - description: 用户电话号
        in: formData
        name: phone
        required: true
        type: string
      - description: 用户id
        in: formData
        name: id
        required: true
        type: string
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: code", "message"}
          schema:
            type: string
        "400":
          description: code", "message"}
          schema:
            type: string
        "500":
          description: code", "message"}
          schema:
            type: string
      summary: 更新用户电话号
      tags:
      - user management
swagger: "2.0"
